- hosts: localhost
  connection: local
  vars:
    vcenter_hostname: your_vcenter_hostname
    vcenter_username: your_vcenter_username
    vcenter_password: your_vcenter_password
    template_name: your_template_name
    vm_name: your_vm_name
    datacenter_name: your_datacenter_name
    cluster_name: your_cluster_name
    datastore_name: your_datastore_name
    resource_pool_name: your_resource_pool_name
    num_cpus: 2
    mem_size_mb: 4096
    disk_size_gb: 20

  tasks:
    - name: Clone VM from template
      vmware_rest_virtual_machine:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        name: "{{ vm_name }}"
        state: present
        datacenter_name: "{{ datacenter_name }}"
        cluster_name: "{{ cluster_name }}"
        resource_pool_name: "{{ resource_pool_name }}"
        datastore_name: "{{ datastore_name }}"
        template_src: "{{ template_name }}"
        hardware:
          num_cpus: "{{ num_cpus }}"
          mem_size_mb: "{{ mem_size_mb }}"
          disks:
            - size_gb: "{{ disk_size_gb }}"
              type: thin
        wait_for_ip_address: true
      register: cloned_vm

    - debug:
        var: cloned_vm
