---
- name: Lookup MoIDs of objects
  hosts: localhost
  gather_facts: false
  vars:
    connection_args:
      vcenter_hostname: 
      vcenter_username: 
      vcenter_password:
      vcenter_validate_certs:
    vm_name:
    folder:
  tasks:
    - name: Lookup MoID of the vm
      ansible.builtin.debug:
        msg: "{{ lookup('vmware.vmware_rest.vm_moid', vm_name, **connection_args) }}"
    - name: Lookup MoID of folder
      ansible.builtin.debug:    
        msg: "{{ lookup('vmware.vmware_rest.folder_moid', folder, **connection_args) }}"
